# Generated by Django 5.1.5 on 2025-01-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_course_duration_course_instructor_course_price'),
        ('student_app', '0003_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
