<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-01-22 10:23
=======
# Generated by Django 5.1.5 on 2025-01-22 09:57
>>>>>>> 34649b6fd3b5c1e58d268679c116ac5b6d426ee3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
                ('isInstructor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication_app.profile')),
                ('department', models.CharField(max_length=100)),
            ],
            bases=('authentication_app.profile',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication_app.profile')),
                ('qualification', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            bases=('authentication_app.profile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication_app.profile')),
                ('school', models.CharField(max_length=20)),
            ],
            bases=('authentication_app.profile',),
        ),
    ]
