# Generated by Django 5.1.5 on 2025-01-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='title_1',
        ),
    ]
