# Generated by Django 5.1.5 on 2025-01-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='student',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
