# Generated by Django 5.1.5 on 2025-01-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_remove_profile_email'),
        ('instructor', '0002_rename_title_video_title_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='authentication_app.instructor'),
        ),
    ]
