# Generated by Django 5.1.5 on 2025-01-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_video_delete_coursevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='title_1',
        ),
    ]
