# Generated by Django 5.1.5 on 2025-01-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_course_duration_course_instructor_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default='Course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='instructor.category'),
        ),
    ]
